<?php

namespace TrendOne\Bundle\TrendVoterBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{
    /**
     * @param string $slug
     *
     * @return \TrendOne\Bundle\TrendVoterBundle\Entity\Campaign
     * @return null
     */
    public function findOneBySlug($slug)
    {
        return $this->findOneBy(array('slug' => $slug));
    }

    /**
     * @param unknown $id
     *
     * @return \TrendOne\Bundle\TrendVoterBundle\Entity\Campaign
     * @return null
     */
    public function findWithJoins($id)
    {
        return $this->createQueryBuilder('campaign')
            ->addSelect('item', 'answer')
            ->leftJoin('campaign.items', 'item')
            ->leftJoin('item.answers', 'answer')
            ->where('campaign = :campaign')
            ->setParameter('campaign', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
