<?php

namespace TrendOne\Bundle\TrendVoterBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignItemRepository extends EntityRepository
{
}
