_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

toa_layout:
    resource: "@ToaLayoutBundle/Controller/"
    type:     annotation
    prefix:   /admin

trend_one_trend_voter_admin:
    resource: "@TrendOneTrendVoterBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

trend_one_trend_voter_frontend:
    resource: "@TrendOneTrendVoterBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /
